-module(netrc_tests).

-include_lib("eunit/include/eunit.hrl").

search_test_() ->
  Search = fun netrc:search/2,
  [?_assertEqual([],
                 Search(#{machine => <<"a.example.com">>},
                        [])),
   ?_assertMatch([#{login := <<"bob">>}],
                 Search(#{machine => <<"a.example.com">>},
                        [#{machine => <<"a.example.com">>,
                           login => <<"bob">>}])),
   ?_assertMatch([#{login := <<"bob">>},
                  #{login := <<"alice">>}],
                 Search(#{machine => <<"a.example.com">>},
                        [#{machine => <<"a.example.com">>,
                           login => <<"bob">>},
                         #{machine => <<"b.example.com">>,
                           login => <<"bob">>},
                         #{machine => <<"a.example.com">>,
                           login => <<"alice">>}])),
   ?_assertMatch([#{login := <<"alice">>}],
                 Search(#{machine => <<"a.example.com">>,
                          login => <<"alice">>},
                        [#{machine => <<"a.example.com">>,
                           login => <<"bob">>},
                         #{machine => <<"a.example.com">>},
                         #{machine => <<"a.example.com">>,
                           login => <<"alice">>}])),
   ?_assertMatch([#{login := <<"alice">>},
                  #{password := <<"foo">>}],
                 Search(#{machine => <<"a.example.com">>,
                          port => 443},
                        [#{machine => <<"a.example.com">>,
                           port => 443,
                           login => <<"alice">>},
                         #{machine => <<"b.example.com">>},
                         #{machine => <<"a.example.com">>,
                           port => 80},
                         #{machine => <<"a.example.com">>,
                           login => <<"bob">>},
                         #{machine => <<"a.example.com">>,
                           port => 443,
                           password => <<"foo">>}]))].
